version: '3.7'
networks:
  databases:
    driver: bridge
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 111rdb060
    networks:
      - databases
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 111rdb060
    networks:
      - databases
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    networks:
      - databases